In [1]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [6]:
a.ndim

1

In [7]:
a.shape

(4,)

In [10]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
b.shape

(2, 3)

In [17]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = np.arange(1,9,2)
b

array([1, 3, 5, 7])

In [20]:
c = np.linspace(0,1,6)
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [22]:
# 提示: (3, 3) 是元组
t = np.ones((3,3))
t

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [27]:
np.random.rand(4) 

array([0.50755507, 0.0211933 , 0.43352176, 0.44631306])

In [28]:
np.random.rand(4)

array([0.23881999, 0.83024573, 0.74476418, 0.586479  ])